import { BaseEngine, EngineConfigSchema, EventEmitter } from '@ai-creative-studio/core';
import { z } from 'zod';
import { v4 as uuidv4 } from 'uuid';

const CommandEngineConfigSchema=EngineConfigSchema.extend({maxHistorySize:z.number().optional().default(100),hotkeysEnabled:z.boolean().optional().default(true)});type CommandEngineConfig=z.infer<typeof CommandEngineConfigSchema>;
export type CommandPriority='high'|'normal'|'low';
export interface ICommand{id:string;type:string;label:string;category:string;description?:string;aliases?:string[];icon?:string;hotkey?:string;priority?:CommandPriority;when?:(context:ICommandContext)=>boolean|string;execute:(context:ICommandContext)=>ICommandResult|Promise<ICommandResult>;undo?:(context:ICommandContext)=>ICommandResult|Promise<ICommandResult>;canExecute?:(context:ICommandContext)=>boolean|string;repeatable?:boolean;requiresConfirmation?:boolean;confirmationMessage?:string|((context:ICommandContext)=>string)}
export interface ICommandContext{projectId?:string;selectedNodes?:string[];currentTime?:number;selectedClips?:string[];selectedTrack?:string;activeWorkspace?:string;activeViewId?:string;copySelection?:()=>ICommandResult|Promise<ICommandResult>;pasteClipboard?:()=>ICommandResult|Promise<ICommandResult>;deleteSelection?:()=>ICommandResult|Promise<ICommandResult>;[key:string]:unknown}
export interface ICommandResult{success:boolean;message?:string;data?:unknown;undoData?:unknown;error?:Error;showNotification?:boolean;notificationType?:'success'|'info'|'warning'|'error';nextCommand?:ICommandRequest}
export interface ICommandRequest{type:string;payload?:unknown;options?:{silent?:boolean;skipHistory?:boolean;priority?:CommandPriority;source?:string}}
export interface IHotkeyBinding{key:string;modifiers:('ctrl'|'alt'|'shift'|'meta')[];commandType:string;scope?:string;when?:()=>boolean}
export interface ICommandHistory{id:string;timestamp:number;command:string;context:ICommandContext;undoData?:unknown}
export interface ICommandEvents{'command:executed':{command:string;result:ICommandResult};'command:undone':{command:string};'command:redone':{command:string};'command:failed':{command:string;error:Error};'hotkey:triggered':{hotkey:string;command:string}}

export class CommandEngine extends BaseEngine{
 private commands=new Map<string,ICommand>();private hotkeyBindings=new Map<string,IHotkeyBinding>();private history:ICommandHistory[]=[];private historyIndex=-1;private maxHistorySize:number;private hotkeysEnabled:boolean;private commandEmitter=new EventEmitter<ICommandEvents>();private macroStack:ICommandRequest[]=[];private isExecutingMacro=false;
 constructor(config:CommandEngineConfig){const parsed=CommandEngineConfigSchema.parse(config);super(parsed);this.maxHistorySize=parsed.maxHistorySize;this.hotkeysEnabled=parsed.hotkeysEnabled;}
 protected async onInitialize():Promise<void>{this.registerCoreCommands();if(this.hotkeysEnabled&&typeof window!=='undefined')window.addEventListener('keydown',this.handleKeyboardEvent)}
 protected override async onDestroy():Promise<void>{if(this.hotkeysEnabled&&typeof window!=='undefined')window.removeEventListener('keydown',this.handleKeyboardEvent);this.commands.clear();this.hotkeyBindings.clear();this.history=[];this.historyIndex=-1}
 registerCommand(command:ICommand):void{if(this.commands.has(command.type))console.warn(`Command ${command.type} already registered, overwriting`);this.commands.set(command.type,command);const binding=this.parseHotkey(command.hotkey,command.type);if(binding)this.hotkeyBindings.set(binding.key,binding)}
 registerCommands(commands:ICommand[]):void{commands.forEach(c=>this.registerCommand(c))} unregisterCommand(type:string):void{const c=this.commands.get(type);if(!c)return;if(c.hotkey){const b=this.parseHotkey(c.hotkey,type);if(b)this.hotkeyBindings.delete(b.key)}this.commands.delete(type)} getCommand(type:string):ICommand|undefined{return this.commands.get(type)} getCommandsByCategory(category:string):ICommand[]{return Array.from(this.commands.values()).filter(c=>c.category===category)} getAllCommands():ICommand[]{return Array.from(this.commands.values())}
 async execute(request:ICommandRequest,context:ICommandContext={}):Promise<ICommandResult>{const command=this.commands.get(request.type);if(!command){const error=new Error(`Unknown command: ${request.type}`);this.commandEmitter.emit('command:failed',{command:request.type,error});return{success:false,error}}const can=command.canExecute?command.canExecute(context):true;if(can!==true&&can!=='enabled')return{success:false,message:typeof can==='string'?can:'Command cannot be executed in current context'};try{const result=await command.execute(context);if(result.success&&command.undo&&!request.options?.skipHistory)this.addToHistory({id:uuidv4(),timestamp:Date.now(),command:request.type,context:{...context},undoData:result.undoData});if(!request.options?.silent)this.commandEmitter.emit('command:executed',{command:request.type,result});return result}catch(error){const normalized=error instanceof Error?error:new Error(String(error));this.commandEmitter.emit('command:failed',{command:request.type,error:normalized});return{success:false,error:normalized}}}
 async undo(context:ICommandContext={}):Promise<ICommandResult|null>{if(this.historyIndex<0)return null;const item=this.history[this.historyIndex];const command=this.commands.get(item.command);if(!command?.undo)return null;try{const result=await command.undo({...item.context,...context,undoData:item.undoData});if(result.success){this.historyIndex--;this.commandEmitter.emit('command:undone',{command:item.command})}return result}catch(error){return{success:false,error:error instanceof Error?error:new Error(String(error))}}}
 async redo(context:ICommandContext={}):Promise<ICommandResult|null>{if(this.historyIndex>=this.history.length-1)return null;const next=this.historyIndex+1;const item=this.history[next];const command=this.commands.get(item.command);if(!command)return null;const merged={...item.context,...context};const can=command.canExecute?command.canExecute(merged):true;if(can!==true&&can!=='enabled')return{success:false,message:'Command cannot be redone in current context'};try{const result=await command.execute(merged);if(result.success){this.historyIndex=next;this.commandEmitter.emit('command:redone',{command:item.command})}return result}catch(error){return{success:false,error:error instanceof Error?error:new Error(String(error))}}}
 canUndo():boolean{return this.historyIndex>=0} canRedo():boolean{return this.historyIndex<this.history.length-1} getHistory():ICommandHistory[]{return[...this.history]} getHistoryIndex():number{return this.historyIndex} clearHistory():void{this.history=[];this.historyIndex=-1}
 registerHotkey(hotkey:string,commandType:string):void{const b=this.parseHotkey(hotkey,commandType);if(b)this.hotkeyBindings.set(b.key,b)} unregisterHotkey(hotkey:string):void{this.hotkeyBindings.delete(hotkey.toLowerCase())} getHotkeyBindings():IHotkeyBinding[]{return Array.from(this.hotkeyBindings.values())}
 beginMacro():void{this.macroStack=[];this.isExecutingMacro=true} addToMacro(request:ICommandRequest):void{if(this.isExecutingMacro)this.macroStack.push(request)} endMacro():ICommandRequest[]{this.isExecutingMacro=false;return[...this.macroStack]}
 async executeMacro(requests:ICommandRequest[],context:ICommandContext):Promise<ICommandResult[]>{const results:ICommandResult[]=[];const initial=this.historyIndex;for(const request of requests){const result=await this.execute(request,{...context});results.push(result);if(!result.success){while(this.historyIndex>initial){const undoResult=await this.undo(context);if(!undoResult?.success)break}break}}return results}
 private handleKeyboardEvent=(event:KeyboardEvent):void=>{if(event.repeat)return;const modifiers:IHotkeyBinding['modifiers']=[];if(event.ctrlKey)modifiers.push('ctrl');if(event.altKey)modifiers.push('alt');if(event.shiftKey)modifiers.push('shift');if(event.metaKey)modifiers.push('meta');const key=[...modifiers,event.key.toLowerCase()].join('+');const binding=this.hotkeyBindings.get(key)||this.hotkeyBindings.get(event.key.toLowerCase());if(binding&&(!binding.when||binding.when())){event.preventDefault();event.stopPropagation();void this.execute({type:binding.commandType},{source:'hotkey'}).then(()=>this.commandEmitter.emit('hotkey:triggered',{hotkey:key,command:binding.commandType}))}}
 private parseHotkey(hotkey:string|undefined,commandType:string):IHotkeyBinding|null{if(!hotkey)return null;const parts=hotkey.toLowerCase().split('+');const modifiers:IHotkeyBinding['modifiers']=[];let key='';for(const part of parts){if(['ctrl','alt','shift','meta'].includes(part))modifiers.push(part as any);else key=part}if(!key)return null;return{key:[...modifiers,key].join('+'),modifiers,commandType}}
 private addToHistory(item:ICommandHistory):void{if(this.historyIndex<this.history.length-1)this.history=this.history.slice(0,this.historyIndex+1);this.history.push(item);if(this.history.length>this.maxHistorySize)this.history.shift();this.historyIndex=this.history.length-1}
 private registerCoreCommands():void{this.registerCommand({id:'core:undo',type:'core:undo',label:'Undo',category:'Core',hotkey:'ctrl+z',execute:async()=>{const r=await this.undo({});return r??{success:false,message:'Nothing to undo'}}});this.registerCommand({id:'core:redo',type:'core:redo',label:'Redo',category:'Core',hotkey:'ctrl+shift+z',execute:async()=>{const r=await this.redo({});return r??{success:false,message:'Nothing to redo'}}});this.registerCommand({id:'core:copy',type:'core:copy',label:'Copy',category:'Edit',hotkey:'ctrl+c',execute:async c=>c.copySelection?c.copySelection():{success:false,message:'Copy is not wired to an editor selection.'}});this.registerCommand({id:'core:paste',type:'core:paste',label:'Paste',category:'Edit',hotkey:'ctrl+v',execute:async c=>c.pasteClipboard?c.pasteClipboard():{success:false,message:'Paste is not wired to an editor clipboard.'}});this.registerCommand({id:'core:delete',type:'core:delete',label:'Delete',category:'Edit',hotkey:'delete',execute:async c=>c.deleteSelection?c.deleteSelection():{success:false,message:'Delete is not wired to an editor selection.'}})}
 on<E extends keyof ICommandEvents>(event:E,listener:(data:ICommandEvents[E])=>void):this{this.commandEmitter.on(event,listener as any);return this} off<E extends keyof ICommandEvents>(event:E,listener:(data:ICommandEvents[E])=>void):this{this.commandEmitter.off(event,listener as any);return this}
 getCapabilities():string[]{return['command:register','command:execute','command:undo','command:redo','command:history','command:hotkeys','command:macros']}
}
