import { BaseEngine, EngineConfigSchema } from '@ai-creative-studio/core';
import { EventEmitter } from 'eventemitter3';
import { z } from 'zod';
import { v4 as uuidv4 } from 'uuid';

const PluginEngineConfigSchema = EngineConfigSchema.extend({
  pluginDirectory: z.string().optional().default('/plugins'),
  allowRemotePlugins: z.boolean().optional().default(false),
  sandboxEnabled: z.boolean().optional().default(true),
});
type PluginEngineConfig = z.infer<typeof PluginEngineConfigSchema>;

export type PluginStatus='uninstalled'|'installing'|'installed'|'loading'|'loaded'|'active'|'error'|'disabled';
export interface IPluginManifest{id:string;name:string;version:string;description?:string;author?:string;license?:string;homepage?:string;repository?:string;keywords?:string[];main:string;icon?:string;minAppVersion?:string;maxAppVersion?:string;engines:Record<string,string>;dependencies?:Record<string,string>;peerDependencies?:Record<string,string>;permissions:IPluginPermission[];extensionPoints:IExtensionPoint[];settings?:IPluginSetting[];}
export interface IPluginPermission{type:'filesystem'|'network'|'clipboard'|'camera'|'microphone'|'notifications'|'storage'|'custom';access:'read'|'write'|'full';description?:string;}
export interface IExtensionPoint{id:string;name:string;description?:string;hooks?:IPluginHook<any>[];panels?:IPanelDefinition[];commands?:ICommandDefinition[];effects?:IEffectDefinition[];}
export interface IPluginHook<TPayload=unknown>{event:string;priority?:number;handler:(payload:TPayload,context:IHookContext)=>unknown|Promise<unknown>;}
export interface IHookContext{pluginId:string;timestamp:number;[key:string]:unknown;}
export interface IPanelDefinition{id:string;type:string;name:string;position:'left'|'right'|'top'|'bottom'|'floating';size?:number;resizable?:boolean;}
export interface ICommandDefinition{id:string;name:string;category:string;hotkey?:string;execute:(context:unknown)=>Promise<void|unknown>;}
export interface IEffectDefinition{id:string;name:string;category:string;parameters?:Record<string,unknown>;apply:(context:unknown,params:unknown)=>Promise<void|unknown>;}
export interface IPluginSetting{key:string;type:'string'|'number'|'boolean'|'select'|'color'|'font'|'file';label:string;description?:string;default:unknown;options?:Array<{value:string;label:string}>;min?:number;max?:number;}
export interface IPlugin{id:string;manifest:IPluginManifest;status:PluginStatus;settings:Record<string,unknown>;instance?:IPluginInstance;error?:Error;enabled:boolean;installedAt?:number;loadedAt?:number;}
export interface IPluginInstance{activate:(context:IPluginContext)=>Promise<void>;deactivate:()=>Promise<void>;updateSettings:(settings:Record<string,unknown>)=>Promise<void>;}
export interface IPluginContext{pluginId:string;version:string;permissions:Set<string>;api:IPluginAPI;}
export interface IPluginAPI{commands:{register:(command:ICommandDefinition)=>void;unregister:(commandId:string)=>void;execute:<T=unknown>(commandId:string,params?:unknown)=>Promise<T>;};events:{on:(event:string,handler:(...args:unknown[])=>void)=>void;off:(event:string,handler:(...args:unknown[])=>void)=>void;emit:(event:string,...args:unknown[])=>void;};storage:{get:<T>(key:string)=>Promise<T|null>;set:<T>(key:string,value:T)=>Promise<void>;remove:(key:string)=>Promise<void>;};ui:{addPanel:(definition:IPanelDefinition)=>void;removePanel:(panelId:string)=>void;showNotification:(message:string,type:'success'|'error'|'info'|'warning')=>void;showModal:(options:{title:string;content:string})=>Promise<void>;};timeline:{addTrack:(type:string,options?:unknown)=>string;addClip:(trackId:string,options?:unknown)=>string;seek:(time:number)=>void;play:()=>void;pause:()=>void;};effects:{register:(effect:IEffectDefinition)=>void;apply:(effectId:string,targetId:string,params?:unknown)=>Promise<unknown>;};}
export interface IPluginEngineEvents{'plugin:installing':{pluginId:string;manifest:IPluginManifest};'plugin:installed':{plugin:IPlugin};'plugin:loading':{pluginId:string};'plugin:loaded':{plugin:IPlugin};'plugin:activated':{pluginId:string};'plugin:deactivated':{pluginId:string};'plugin:error':{pluginId:string;error:Error};'plugin:uninstalled':{pluginId:string};}

export class PluginEngine extends BaseEngine{
 private plugins=new Map<string,IPlugin>();private hooks=new Map<string,Array<{pluginId:string;handler:IPluginHook['handler'];priority:number}>>();private emitter=new EventEmitter<IPluginEngineEvents>();private pluginEvents=new Map<string,EventEmitter<any>>();private pluginStorage=new Map<string,Map<string,unknown>>();private commands=new Map<string,{pluginId:string;definition:ICommandDefinition}>();private panels=new Map<string,{pluginId:string;definition:IPanelDefinition}>();private effects=new Map<string,{pluginId:string;definition:IEffectDefinition}>();private sandboxEnabled:boolean;private allowRemotePlugins:boolean;private pluginDirectory:string;
 constructor(config:PluginEngineConfig){const parsed=PluginEngineConfigSchema.parse(config);super(parsed as any);this.sandboxEnabled=parsed.sandboxEnabled;this.allowRemotePlugins=parsed.allowRemotePlugins;this.pluginDirectory=parsed.pluginDirectory;}
 protected async onInitialize():Promise<void>{}
 protected override async onDestroy():Promise<void>{for(const p of this.plugins.values())if(p.status==='active'&&p.instance)await p.instance.deactivate().catch(()=>{});this.plugins.clear();this.hooks.clear();this.pluginEvents.clear();this.pluginStorage.clear();this.commands.clear();this.panels.clear();this.effects.clear();}
 async installPlugin(manifest:IPluginManifest,_source?:string):Promise<IPlugin>{this.validateManifest(manifest);if(this.plugins.has(manifest.id))throw new Error(`Plugin ${manifest.id} is already installed`);const plugin:IPlugin={id:manifest.id,manifest,status:'installed',settings:{},enabled:true,installedAt:Date.now()};for(const s of manifest.settings??[])plugin.settings[s.key]=s.default;this.plugins.set(plugin.id,plugin);this.pluginEvents.set(plugin.id,new EventEmitter());this.pluginStorage.set(plugin.id,new Map());this.emitter.emit('plugin:installed',{plugin});return plugin;}
 async uninstallPlugin(pluginId:string):Promise<void>{const p=this.requirePlugin(pluginId);if(p.status==='active')await this.deactivatePlugin(pluginId);for(const [id,c]of this.commands)if(c.pluginId===pluginId)this.commands.delete(id);for(const [id,c]of this.panels)if(c.pluginId===pluginId)this.panels.delete(id);for(const [id,c]of this.effects)if(c.pluginId===pluginId)this.effects.delete(id);for(const [event,list]of this.hooks){const next=list.filter(h=>h.pluginId!==pluginId);if(next.length)this.hooks.set(event,next);else this.hooks.delete(event);}this.plugins.delete(pluginId);this.pluginEvents.delete(pluginId);this.pluginStorage.delete(pluginId);this.emitter.emit('plugin:uninstalled',{pluginId});}
 async loadPlugin(pluginId:string):Promise<void>{const p=this.requirePlugin(pluginId);if(p.status==='loaded'||p.status==='active')return;p.status='loading';this.emitter.emit('plugin:loading',{pluginId});try{p.instance=await this.loadPluginModule(p,this.createPluginContext(p));p.status='loaded';p.loadedAt=Date.now();this.registerHooks(p);this.registerExtensionPoints(p);this.emitter.emit('plugin:loaded',{plugin:p});}catch(error){p.status='error';p.error=error instanceof Error?error:new Error(String(error));this.emitter.emit('plugin:error',{pluginId,error:p.error});throw p.error;}}
 async activatePlugin(pluginId:string):Promise<void>{const p=this.requirePlugin(pluginId);if(p.status!=='loaded'&&p.status!=='active')await this.loadPlugin(pluginId);if(p.instance){await p.instance.activate(this.createPluginContext(p));}p.status='active';p.enabled=true;this.emitter.emit('plugin:activated',{pluginId});}
 async deactivatePlugin(pluginId:string):Promise<void>{const p=this.requirePlugin(pluginId);if(p.status!=='active')return;if(p.instance)await p.instance.deactivate();p.status='loaded';p.enabled=false;this.emitter.emit('plugin:deactivated',{pluginId});}
 private async loadPluginModule(_plugin:IPlugin,_context:IPluginContext):Promise<IPluginInstance>{throw new Error('Plugin module loading requires a trusted runtime adapter; manifest metadata alone cannot execute arbitrary code.');}
 private requirePlugin(id:string):IPlugin{const p=this.plugins.get(id);if(!p)throw new Error(`Plugin ${id} not found`);return p;}
 private createPluginContext(plugin:IPlugin):IPluginContext{const permissions=new Set(plugin.manifest.permissions.map(p=>p.type));return{pluginId:plugin.id,version:plugin.manifest.version,permissions,api:this.createPluginAPI(plugin)};}
 private requirePermission(plugin:IPlugin,permission:string):void{if(!plugin.manifest.permissions.some(p=>p.type===permission))throw new Error(`Plugin ${plugin.id} does not have ${permission} permission`);}
 private createPluginAPI(plugin:IPlugin):IPluginAPI{const eventBus=()=>this.pluginEvents.get(plugin.id) as EventEmitter<any>;return{commands:{register:(definition)=>{if(this.commands.has(definition.id))throw new Error(`Command ${definition.id} already registered`);this.commands.set(definition.id,{pluginId:plugin.id,definition});},unregister:(id)=>{const c=this.commands.get(id);if(c?.pluginId===plugin.id)this.commands.delete(id);},execute:async<T>(id,params?)=>{const c=this.commands.get(id);if(!c)throw new Error(`Command ${id} not found`);return await c.definition.execute(params) as T;}},events:{on:(e,h)=>eventBus().on(e,h),off:(e,h)=>eventBus().off(e,h),emit:(e,...a)=>eventBus().emit(e,...a)},storage:{get:async<T>(key)=>{this.requirePermission(plugin,'storage');return (this.pluginStorage.get(plugin.id)?.get(key) as T|undefined)??null;},set:async<T>(key,value)=>{this.requirePermission(plugin,'storage');this.pluginStorage.get(plugin.id)?.set(key,value);},remove:async key=>{this.requirePermission(plugin,'storage');this.pluginStorage.get(plugin.id)?.delete(key);}},ui:{addPanel:d=>{this.panels.set(d.id,{pluginId:plugin.id,definition:d});},removePanel:id=>{const p=this.panels.get(id);if(p?.pluginId===plugin.id)this.panels.delete(id);},showNotification:(message,type)=>{this.emitter.emit('plugin:loaded',{plugin:{...plugin,error:undefined,settings:{...plugin.settings},status:type==='error'?'error':plugin.status,enabled:plugin.enabled}} as IPlugin);console.info(`[plugin:${plugin.id}] ${type}: ${message}`);},showModal:async()=>{}},timeline:{addTrack:(_type)=>uuidv4(),addClip:(_trackId)=>uuidv4(),seek:(_time)=>{},play:()=>{},pause:()=>{}},effects:{register:d=>{this.effects.set(d.id,{pluginId:plugin.id,definition:d});},apply:async(id,targetId,params)=>{const effect=this.effects.get(id);if(!effect)throw new Error(`Effect ${id} not found`);return await effect.definition.apply({targetId,pluginId:plugin.id},params);}}};}
 private registerHooks(plugin:IPlugin):void{for(const ep of plugin.manifest.extensionPoints){for(const hook of ep.hooks??[]){const list=this.hooks.get(hook.event)||[];list.push({pluginId:plugin.id,handler:hook.handler,priority:hook.priority??10});list.sort((a,b)=>a.priority-b.priority);this.hooks.set(hook.event,list);}}}
 private registerExtensionPoints(plugin:IPlugin):void{for(const ep of plugin.manifest.extensionPoints){for(const command of ep.commands??[])this.commands.set(command.id,{pluginId:plugin.id,definition:command});for(const panel of ep.panels??[])this.panels.set(panel.id,{pluginId:plugin.id,definition:panel});for(const effect of ep.effects??[])this.effects.set(effect.id,{pluginId:plugin.id,definition:effect});}}
 async executeHook<TPayload=unknown,TResult=unknown>(event:string,payload:TPayload):Promise<TResult[]>{const list=this.hooks.get(event)||[];const results<TResult[]>=[];for(const item of list){const plugin=this.plugins.get(item.pluginId);if(!plugin?.enabled||plugin.status!=='active')continue;try{const result=await item.handler(payload,{pluginId:item.pluginId,timestamp:Date.now()});if(result!==undefined)results.push(result as TResult);}catch(error){const err=error instanceof Error?error:new Error(String(error));this.emitter.emit('plugin:error',{pluginId:item.pluginId,error:err});}}return results;}
 getPlugin(id:string):IPlugin|undefined{return this.plugins.get(id);}getAllPlugins():IPlugin[]{return[...this.plugins.values()];}getPluginsByStatus(status:PluginStatus):IPlugin[]{return[...this.plugins.values()].filter(p=>p.status===status);}
 validateManifest(manifest:IPluginManifest):void{if(!manifest.id||!manifest.name||!manifest.version||!manifest.main)throw new Error('Plugin manifest requires id, name, version and main');if(!Array.isArray(manifest.permissions))throw new Error('Plugin manifest permissions must be an array');if(!Array.isArray(manifest.extensionPoints))throw new Error('Plugin manifest extensionPoints must be an array');if(!this.allowRemotePlugins&&/^https?:\/\//i.test(manifest.main))throw new Error('Remote plugin modules are disabled');}
 updatePluginSettings(id:string,settings:Record<string,unknown>):void{const p=this.requirePlugin(id);p.settings={...p.settings,...settings};if(p.instance?.updateSettings)void p.instance.updateSettings(p.settings);}
 getPluginSettings(id:string):Record<string,unknown>|undefined{return this.plugins.get(id)?.settings;}
 enablePlugin(id:string):void{const p=this.plugins.get(id);if(p&&p.status!=='error'){p.enabled=true;p.status=p.status==='disabled'?'loaded':p.status;}}
 disablePlugin(id:string):void{const p=this.plugins.get(id);if(p){p.enabled=false;p.status='disabled';}}
 getRegisteredCommands():ICommandDefinition[]{return[...this.commands.values()].map(x=>x.definition);}
 getRegisteredPanels():IPanelDefinition[]{return[...this.panels.values()].map(x=>x.definition);}
 getRegisteredEffects():IEffectDefinition[]{return[...this.effects.values()].map(x=>x.definition);}
 on<E extends keyof IPluginEngineEvents>(event:E,listener:(data:IPluginEngineEvents[E])=>void):this{this.emitter.on(event,listener as any);return this;}
 off<E extends keyof IPluginEngineEvents>(event:E,listener:(data:IPluginEngineEvents[E])=>void):this{this.emitter.off(event,listener as any);return this;}
 getCapabilities():string[]{return['plugin:install','plugin:uninstall','plugin:load','plugin:activate','plugin:deactivate','plugin:settings','plugin:hooks','plugin:commands','plugin:panels','plugin:effects','plugin:storage','plugin:permissions'];}
}
