import { TimelineInteractionController, type IClip, type ITrack, type ITimelineState } from './index.js';
function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message); }
const close=(a:number,b:number,eps=1/30+1e-6)=>Math.abs(a-b)<=eps;
const makeClip=(id:string,name:string,start:number,duration:number,sourceDuration=20):IClip=>({id,name,startTime:start,endTime:start+duration,trimStart:0,trimEnd:duration,duration,speed:1,opacity:1,effects:[],animations:[],keyframes:[],metadata:{sourceDuration,mediaType:'video'}});
const makeState=(tracks:ITrack[]):ITimelineState=>({tracks,currentTime:0,duration:Math.max(0,...tracks.flatMap(t=>t.clips.map(c=>c.endTime))),isPlaying:false,playbackRate:1,loopEnabled:false,markers:[],snaps:[]});
export async function runRealEditingScenario():Promise<void>{
 const ctl=new TimelineInteractionController({id:'e2e-editing',name:'Vireon E2E Editing',frameRate:30,snappingTolerance:.05}); await ctl.initialize();
 ctl.loadState(makeState([
  {id:'v1',name:'Main Video',type:'video',clips:[makeClip('a','A',0,3),makeClip('b','B',3,3),makeClip('c','C',6,3)],muted:false,locked:false,visible:true,height:78,order:0,magnetic:true},
  {id:'v2',name:'B-Roll',type:'video',clips:[makeClip('d','D',0,9)],muted:false,locked:false,visible:true,height:78,order:1,magnetic:false},
  {id:'a1',name:'Audio',type:'audio',clips:[makeClip('music','Music',0,9,9)],muted:false,locked:false,visible:true,height:72,order:2,magnetic:false},
 ]));
 const beforeSplit=ctl.getState(); ctl.beginInteraction(); const split=ctl.engine.splitClip('b',4.5); assert(split?.length===2,'blade failed'); ctl.commitInteraction('Blade'); assert(ctl.getState().tracks[0].clips.length===4,'blade count failed'); ctl.undo(); assert(ctl.getState().tracks[0].clips.length===3,'undo failed'); ctl.redo(); assert(ctl.getState().tracks[0].clips.length===4,'redo failed'); assert(beforeSplit.tracks[0].clips.length===3,'snapshot mutated');
 const rightId=ctl.getState().tracks[0].clips.find(c=>c.id!=='a'&&c.id!=='b')?.id; assert(rightId,'right clip missing'); const oldRight=ctl.getState().tracks[0].clips.find(c=>c.id===rightId)!.startTime; ctl.beginInteraction(); ctl.preview({type:'trim-end',clipId:'b',deltaTime:.5}); ctl.commitInteraction('Ripple Trim'); assert(ctl.getState().tracks[0].clips.find(c=>c.id===rightId)!.startTime>oldRight,'ripple trim did not move following clip');
 const insertClip=makeClip('insert','Insert',0,1.5); assert(ctl.insertClip(insertClip,'v1',1,'insert'),'insert failed'); const main=ctl.getState().tracks[0]; assert(main.clips.some(c=>c.id==='insert'),'insert missing'); assert(main.clips.length>=6,'insert did not shift/split content');
 const overwrite=makeClip('overwrite','Overwrite',0,2); assert(ctl.insertClip(overwrite,'v1',2,'overwrite'),'overwrite failed'); assert(ctl.getState().tracks[0].clips.some(c=>c.id==='overwrite'),'overwrite missing');
 ctl.loadState(makeState([{id:'r',name:'Roll',type:'video',clips:[makeClip('r1','R1',0,3),makeClip('r2','R2',3,3)],muted:false,locked:false,visible:true,height:78,order:0,magnetic:true}])); assert(ctl.roll('r1','r2',4),'roll failed'); const roll=ctl.getState().tracks[0].clips; assert(close(roll[0].endTime,4)&&close(roll[1].startTime,4),'roll boundary failed');
 const slipState=makeState([{id:'s',name:'Slip',type:'video',clips:[makeClip('s1','S',2,3,20)],muted:false,locked:false,visible:true,height:78,order:0,magnetic:true}]); const sc=slipState.tracks[0].clips[0]; sc.trimStart=2; sc.trimEnd=5; ctl.loadState(slipState); const oldStart=sc.startTime,oldDuration=sc.duration; assert(ctl.slip('s1',1),'slip failed'); const slipped=ctl.getState().tracks[0].clips[0]; assert(close(slipped.startTime,oldStart)&&close(slipped.duration,oldDuration)&&close(slipped.trimStart,3),'slip geometry failed');
 ctl.loadState(makeState([{id:'sl',name:'Slide',type:'video',clips:[makeClip('p','P',0,2),makeClip('m','M',2,2),makeClip('n','N',4,2)],muted:false,locked:false,visible:true,height:78,order:0,magnetic:true}])); assert(ctl.slide('m',.5),'slide failed'); const slid=ctl.getState().tracks[0].clips; assert(close(slid.find(c=>c.id==='m')!.startTime,2.5)&&close(slid.find(c=>c.id==='m')!.duration,2),'slide center failed'); assert(close(slid.find(c=>c.id==='p')!.endTime,2.5)&&close(slid.find(c=>c.id==='n')!.startTime,4.5),'slide neighbors failed');
 ctl.loadState(makeState([{id:'pro',name:'Professional',type:'video',clips:[makeClip('p1','Pro',0,4,20),makeClip('p2','Next',4,2,20)],muted:false,locked:false,visible:true,height:78,order:0,magnetic:true}])); assert(ctl.setClipSpeed('p1',100,true),'100x failed'); assert(ctl.setSpeedCurveProfessional('p1',[{time:0,speed:.1},{time:2,speed:50},{time:4,speed:100}]),'curve failed'); assert(ctl.setTransition('p1','out','crossfade',1),'transition failed'); assert(ctl.addKeyframe('p1',{time:1,property:'opacity',value:.5,easing:'ease-in'}),'keyframe failed'); const pro=ctl.getState().tracks[0].clips.find(c=>c.id==='p1')!; assert(pro.speed===100&&pro.metadata?.speedMode==='curve'&&pro.keyframes.length===1&&pro.transitionOut?.duration===1,'professional edits persistence failed');
 const freezeBefore=ctl.getState().tracks[0].clips.find(c=>c.id==='p2')!.startTime; assert(ctl.freezeFrame('p1',1),'freeze failed'); const frozen=ctl.getState().tracks[0].clips; assert(frozen.find(c=>c.id==='p1')!.metadata?.speedMode==='freeze','freeze metadata missing'); assert(frozen.find(c=>c.id==='p2')!.startTime>freezeBefore,'freeze ripple failed');
 const linkedA=makeClip('va','Video',0,2),linkedB=makeClip('aa','Audio',0,2,2); ctl.loadState(makeState([{id:'lv',name:'Video',type:'video',clips:[linkedA],muted:false,locked:false,visible:true,height:78,order:0,magnetic:true},{id:'la',name:'Audio',type:'audio',clips:[linkedB],muted:false,locked:false,visible:true,height:72,order:1,magnetic:false}])); ctl.select('va'); ctl.select('aa',true); assert(ctl.linkSelected(),'link failed'); assert(ctl.rippleTrimLinked('va','end',1.5),'linked trim failed'); const linkedState=ctl.getState(); assert(linkedState.tracks[0].clips[0].linkedClipIds?.includes('aa'),'link relation missing');
 const final=ctl.getState(); for(const track of final.tracks)for(const c of track.clips){assert(c.endTime>c.startTime,'invalid interval');assert(c.duration>0,'invalid duration');assert(c.speed>=.1&&c.speed<=100,'invalid speed');} await ctl.engine.destroy(); console.log('real editing scenario: PASS');
}
if(import.meta.url.endsWith('/e2e-editing-test.ts'))runRealEditingScenario().catch(error=>{console.error(error);process.exitCode=1;});
