import { BaseEngine, EngineConfigSchema, Color, Vec2, Bounds } from '@ai-creative-studio/core';
import { EventEmitter } from 'eventemitter3';
import { z } from 'zod';

const RenderingEngineConfigSchema = EngineConfigSchema.extend({ useWebGL:z.boolean().optional().default(false), antialiasing:z.boolean().optional().default(true), backgroundColor:z.object({r:z.number(),g:z.number(),b:z.number()}).optional(), maxTextureSize:z.number().optional().default(4096) });
type RenderingEngineConfig=z.infer<typeof RenderingEngineConfigSchema>;
export interface IRenderTarget{id:string;type:'canvas'|'texture'|'framebuffer';width:number;height:number;context:CanvasRenderingContext2D|WebGLRenderingContext|WebGL2RenderingContext|null}
export interface IRenderCommand{type:'fill'|'stroke'|'image'|'text'|'clip'|'transform'|'filter'|'path';params:Record<string,unknown>;order:number}
export interface IRenderLayer{id:string;name:string;visible:boolean;locked:boolean;opacity:number;blendMode:BlendMode;commands:IRenderCommand[];bounds:Bounds}
export type BlendMode='normal'|'multiply'|'screen'|'overlay'|'darken'|'lighten'|'color-dodge'|'color-burn'|'hard-light'|'soft-light'|'difference'|'exclusion'|'hue'|'saturation'|'color'|'luminosity';
export interface IRenderTargetInfo{width:number;height:number;pixelRatio:number;devicePixelRatio:number}
export interface IRenderContext{ctx:CanvasRenderingContext2D|WebGLRenderingContext|WebGL2RenderingContext;target:IRenderTargetInfo;time:number;frame:number;deltaTime:number}
export type RenderCallback=(context:IRenderContext)=>void;
export interface IRendererEvents{'renderer:frame-start':{time:number;frame:number};'renderer:frame-end':{time:number;frame:number;renderTime:number};'renderer:resize':{width:number;height:number};'renderer:error':{error:Error};'renderer:webgl-context-lost':{};'renderer:webgl-context-restored':{}}
const nowMs=()=>typeof globalThis.performance!=='undefined'&&typeof globalThis.performance.now==='function'?globalThis.performance.now():Date.now();

export class RenderingEngine extends BaseEngine{
 private canvas:HTMLCanvasElement|null=null;private ctx:CanvasRenderingContext2D|WebGLRenderingContext|WebGL2RenderingContext|null=null;private gl:WebGLRenderingContext|WebGL2RenderingContext|null=null;private usingWebGL:boolean;private renderers=new Map<string,RenderCallback>();private layers=new Map<string,IRenderLayer>();private layerOrder:string[]=[];private animationFrameId:number|null=null;private isRendering=false;private width=1920;private height=1080;private pixelRatio=1;private rendererEmitter=new EventEmitter<IRendererEvents>();private shaderCache=new Map<string,WebGLProgram>();private textureCache=new Map<string,WebGLTexture>();private bufferCache=new Map<string,WebGLBuffer>();private currentFrame=0;
 constructor(config:RenderingEngineConfig){const parsed=RenderingEngineConfigSchema.parse(config);super(parsed);this.usingWebGL=parsed.useWebGL;}
 protected async onInitialize():Promise<void>{}
 protected override async onDestroy():Promise<void>{this.stopRendering();if(this.gl){this.shaderCache.forEach(p=>this.gl!.deleteProgram(p));this.textureCache.forEach(t=>this.gl!.deleteTexture(t));this.bufferCache.forEach(b=>this.gl!.deleteBuffer(b));}this.ctx=null;this.gl=null;this.canvas=null;this.renderers.clear();this.layers.clear();this.layerOrder=[];}
 setCanvas(canvas:HTMLCanvasElement):void{this.canvas=canvas;const experimentalWebGL=this.usingWebGL&&canvas.dataset.renderMode==='webgl-experimental';if(experimentalWebGL){const context=canvas.getContext('webgl2')||canvas.getContext('webgl');if(context){this.gl=context as WebGLRenderingContext;this.ctx=context as WebGLRenderingContext;this.initWebGL();}else{this.ctx=canvas.getContext('2d');this.usingWebGL=false;}}else this.ctx=canvas.getContext('2d');this.resize(canvas.width||this.width,canvas.height||this.height);}
 setOutputResolution(width:number,height:number):void{this.width=Math.max(1,Math.floor(width));this.height=Math.max(1,Math.floor(height));if(this.canvas){this.canvas.width=this.width;this.canvas.height=this.height;this.resize(this.width,this.height);}}
 resize(width:number,height:number):void{this.width=Math.max(1,Math.floor(width));this.height=Math.max(1,Math.floor(height));this.pixelRatio=typeof window!=='undefined'?window.devicePixelRatio||1:1;if(this.canvas){this.canvas.style.width=`${this.width}px`;this.canvas.style.height=`${this.height}px`;if(this.usingWebGL&&this.gl)this.gl.viewport(0,0,this.width*this.pixelRatio,this.height*this.pixelRatio);}this.rendererEmitter.emit('renderer:resize',{width:this.width,height:this.height});}
 private initWebGL():void{if(!this.gl)return;this.gl.enable(this.gl.BLEND);this.gl.blendFunc(this.gl.SRC_ALPHA,this.gl.ONE_MINUS_SRC_ALPHA);this.gl.enable(this.gl.DEPTH_TEST);this.gl.depthFunc(this.gl.LEQUAL);}
 registerRenderer(id:string,callback:RenderCallback):void{this.renderers.set(id,callback)} unregisterRenderer(id:string):void{this.renderers.delete(id)} addLayer(layer:IRenderLayer):void{if(!this.layers.has(layer.id))this.layerOrder.push(layer.id);this.layers.set(layer.id,layer)} removeLayer(id:string):void{this.layers.delete(id);this.layerOrder=this.layerOrder.filter(x=>x!==id)} getLayer(id:string):IRenderLayer|undefined{return this.layers.get(id)} updateLayer(id:string,updates:Partial<IRenderLayer>):void{const layer=this.layers.get(id);if(layer)Object.assign(layer,updates)}
 clearCanvas(color?:Color):void{if(!this.ctx)return;if(this.usingWebGL&&this.gl){const c=color||{r:0,g:0,b:0,a:1};this.gl.clearColor(c.r,c.g,c.b,c.a??1);this.gl.clear(this.gl.COLOR_BUFFER_BIT|this.gl.DEPTH_BUFFER_BIT);}else if(typeof CanvasRenderingContext2D!=='undefined'&&this.ctx instanceof CanvasRenderingContext2D){this.ctx.clearRect(0,0,this.width,this.height);if(color){this.ctx.fillStyle=`rgba(${Math.round(color.r*255)}, ${Math.round(color.g*255)}, ${Math.round(color.b*255)}, ${color.a??1})`;this.ctx.fillRect(0,0,this.width,this.height);}}}
 startRendering():void{if(this.isRendering)return;this.isRendering=true;this.renderLoop()}
 stopRendering():void{this.isRendering=false;if(this.animationFrameId!==null){if(typeof cancelAnimationFrame!=='undefined')cancelAnimationFrame(this.animationFrameId);else clearTimeout(this.animationFrameId as unknown as ReturnType<typeof setTimeout>);this.animationFrameId=null}}
 render(time?:number):void{const start=nowMs(),renderTime=time??0;this.rendererEmitter.emit('renderer:frame-start',{time:renderTime,frame:this.currentFrame});this.clearCanvas();for(const id of this.layerOrder){const layer=this.layers.get(id);if(layer?.visible)this.renderLayer(layer,renderTime)}if(this.ctx){const context:IRenderContext={ctx:this.ctx,target:{width:this.width,height:this.height,pixelRatio:this.pixelRatio,devicePixelRatio:typeof window!=='undefined'?window.devicePixelRatio||1:1},time:renderTime,frame:this.currentFrame,deltaTime:0};this.renderers.forEach(cb=>{try{cb(context)}catch(error){this.rendererEmitter.emit('renderer:error',{error:error instanceof Error?error:new Error(String(error))})}})}this.rendererEmitter.emit('renderer:frame-end',{time:renderTime,frame:this.currentFrame,renderTime:nowMs()-start});this.currentFrame++}
 private renderLoop=():void=>{if(!this.isRendering)return;this.render();if(typeof requestAnimationFrame!=='undefined')this.animationFrameId=requestAnimationFrame(this.renderLoop);else this.animationFrameId=setTimeout(this.renderLoop,16) as unknown as number};
 private renderLayer(layer:IRenderLayer,_time:number):void{if(!this.ctx||typeof CanvasRenderingContext2D==='undefined'||!(this.ctx instanceof CanvasRenderingContext2D))return;const ctx=this.ctx;ctx.save();ctx.globalAlpha=Math.max(0,Math.min(1,layer.opacity));ctx.globalCompositeOperation=layer.blendMode as GlobalCompositeOperation;for(const command of [...layer.commands].sort((a,b)=>a.order-b.order))this.executeCommand(ctx,command);ctx.restore()}
 private executeCommand(ctx:CanvasRenderingContext2D,command:IRenderCommand):void{const p=command.params;switch(command.type){case'fill':{const c=p.color as Color|undefined;if(c)ctx.fillStyle=`rgba(${Math.round(c.r*255)}, ${Math.round(c.g*255)}, ${Math.round(c.b*255)}, ${c.a??1})`;ctx.fillRect(p.x as number,p.y as number,p.width as number,p.height as number);break;}case'stroke':{const c=p.color as Color|undefined;if(c)ctx.strokeStyle=`rgba(${Math.round(c.r*255)}, ${Math.round(c.g*255)}, ${Math.round(c.b*255)}, ${c.a??1})`;ctx.lineWidth=(p.lineWidth as number)??1;ctx.strokeRect(p.x as number,p.y as number,p.width as number,p.height as number);break;}case'image':{const image=p.image as CanvasImageSource;if(p.width!==undefined&&p.height!==undefined)ctx.drawImage(image,p.x as number,p.y as number,p.width as number,p.height as number);else ctx.drawImage(image,p.x as number,p.y as number);break;}case'text':{ctx.font=(p.font as string)||'16px sans-serif';ctx.textAlign=(p.textAlign as CanvasTextAlign)||'left';ctx.textBaseline=(p.textBaseline as CanvasTextBaseline)||'top';if(p.fillStyle){ctx.fillStyle=p.fillStyle as string;ctx.fillText(p.text as string,p.x as number,p.y as number)}if(p.strokeStyle){ctx.strokeStyle=p.strokeStyle as string;ctx.strokeText(p.text as string,p.x as number,p.y as number)}break;}case'filter':ctx.filter=(p.filter as string)||'none';break;case'clip':{const path=p.path as Vec2[];ctx.beginPath();path.forEach((pt,i)=>i?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y));ctx.closePath();ctx.clip();break;}case'transform':{if(p.translate){const t=p.translate as Vec2;ctx.translate(t.x,t.y)}if(p.scale){const s=p.scale as Vec2;ctx.scale(s.x,s.y)}if(p.rotate!==undefined)ctx.rotate(p.rotate as number);if(p.transform){const m=p.transform as[number,number,number,number,number,number];ctx.transform(...m)}break;}case'path':{const commands=p.commands as Array<{type:string;data:any}>;ctx.beginPath();for(const cmd of commands){switch(cmd.type){case'moveTo':ctx.moveTo(cmd.data.x,cmd.data.y);break;case'lineTo':ctx.lineTo(cmd.data.x,cmd.data.y);break;case'bezierCurveTo':ctx.bezierCurveTo(cmd.data.cp1.x,cmd.data.cp1.y,cmd.data.cp2.x,cmd.data.cp2.y,cmd.data.end.x,cmd.data.end.y);break;case'quadraticCurveTo':ctx.quadraticCurveTo(cmd.data.cp.x,cmd.data.cp.y,cmd.data.end.x,cmd.data.end.y);break;case'arc':ctx.arc(cmd.data.center.x,cmd.data.center.y,cmd.data.radius,cmd.data.startAngle,cmd.data.endAngle);break;case'closePath':ctx.closePath();break}}if(p.fill){ctx.fillStyle=p.fill as string;ctx.fill()}if(p.stroke){ctx.strokeStyle=p.stroke as string;ctx.stroke()}break;}}}
 getResolution(){return{width:this.width,height:this.height}} getContext(){return this.ctx}
 onRenderer<E extends keyof IRendererEvents>(event:E,listener:(data:IRendererEvents[E])=>void):this{this.rendererEmitter.on(event,listener as any);return this} offRenderer<E extends keyof IRendererEvents>(event:E,listener:(data:IRendererEvents[E])=>void):this{this.rendererEmitter.off(event,listener as any);return this}
 getCapabilities():string[]{return['render:canvas2d','render:layers','render:blend-modes','render:commands','render:filters','render:paths','render:transforms','render:resize','render:events'];}
}
