import type { Express, Request, Response } from 'express';
import type Database from 'better-sqlite3';
import { randomUUID } from 'node:crypto';
import { existsSync, unlinkSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { parseWithOpenAI, type EditCommand } from './aiProvider.js';

const ROOT=resolve(process.cwd(),'../..');
const EXPORTS=join(ROOT,'data','exports');
mkdirSync(EXPORTS,{recursive:true});
const hasAudio=(path:string)=>{try{return execFileSync('ffprobe',['-v','error','-select_streams','a:0','-show_entries','stream=codec_type','-of','default=nw=1:nk=1',path],{encoding:'utf8',timeout:30000}).trim()==='audio';}catch{return false;}};
const escText=(text:string)=>String(text).replace(/\\/g,'\\\\').replace(/:/g,'\\:').replace(/'/g,"\\'").replace(/%/g,'\\%').replace(/\n/g,'\\n');
const atempo=(speed:number)=>{let x=Math.max(.25,Math.min(4,speed));const p:string[]=[];while(x>2){p.push('atempo=2');x/=2;}while(x<.5){p.push('atempo=0.5');x/=.5;}p.push(`atempo=${x}`);return p.join(',');};

async function advancedRender(req:Request,res:Response,db:Database.Database){
  try{
    const id=String(req.params.id);const p:any=db.prepare('SELECT * FROM projects WHERE id=?').get(id);if(!p)return res.status(404).json({error:'Project not found'});
    const timeline=JSON.parse(p.timeline_json);const vtrack=timeline.tracks.find((t:any)=>t.type==='video');const videos=(vtrack?.clips||[]).filter((c:any)=>c.duration>0);if(!videos.length)return res.status(422).json({error:'No video clips'});
    const inputs:string[]=[];let next=0;const vfLabels:string[]=[];const afLabels:string[]=[];let totalVideo=0;
    for(const clip of videos){
      const asset:any=db.prepare('SELECT * FROM assets WHERE id=?').get(clip.assetId);if(!asset||!existsSync(asset.path))return res.status(404).json({error:`Media missing for ${clip.name}`});
      const audio=hasAudio(asset.path);const input=next;inputs.push('-ss',String(clip.trimStart),'-t',String(Math.max(.01,clip.trimEnd-clip.trimStart)),'-i',asset.path);next+=audio?1:2;if(!audio)inputs.push('-f','lavfi','-t',String(Math.max(.01,clip.trimEnd-clip.trimStart)),'-i','anullsrc=channel_layout=stereo:sample_rate=48000');
      const speed=Math.max(.25,Math.min(4,Number(clip.speed||1)));const dur=Math.max(.01,(clip.trimEnd-clip.trimStart)/speed);totalVideo+=dur;
      const vf:string[]=['setpts=PTS-STARTPTS',`setpts=PTS/${speed}`];if(clip.flipH)vf.push('hflip');if(clip.flipV)vf.push('vflip');const rot=((Number(clip.rotate||0)%360)+360)%360;if(rot===90)vf.push('transpose=1');else if(rot===180)vf.push('hflip','vflip');else if(rot===270)vf.push('transpose=2');
      const br=Number(clip.brightness||0),ct=Number(clip.contrast||1),sat=Number(clip.saturation||1);if(br!==0||ct!==1||sat!==1||clip.grayscale)vf.push(`eq=brightness=${br}:contrast=${ct}:saturation=${clip.grayscale?0:sat}`);
      if((clip.effects||[]).includes('blur'))vf.push('boxblur=4:1');if((clip.effects||[]).includes('vignette'))vf.push('vignette=PI/4');
      const texts=(timeline.tracks.find((t:any)=>t.type==='text')?.clips||[]).filter((t:any)=>t.startTime<clip.endTime&&t.endTime>clip.startTime&&t.text);for(const t of texts){const ls=Math.max(0,t.startTime-clip.startTime),le=Math.min(dur,t.endTime-clip.startTime);if(le>ls)vf.push(`drawtext=text='${escText(t.text)}':fontcolor=${t.color||'white'}:fontsize=${Number(t.fontSize||48)}:x=(w-text_w)/2:y=h*0.82:enable='between(t,${ls},${le})'`);}
      if(Number(clip.fadeIn||0)>0)vf.push(`fade=t=in:st=0:d=${Math.min(Number(clip.fadeIn),dur)}`);if(Number(clip.fadeOut||0)>0){const fo=Math.min(Number(clip.fadeOut),dur);vf.push(`fade=t=out:st=${Math.max(0,dur-fo)}:d=${fo}`);}
      vf.push('scale=1280:720:force_original_aspect_ratio=decrease','pad=1280:720:(ow-iw)/2:(oh-ih)/2','setsar=1');
      const vi=vfLabels.length;vfLabels.push(`[${input}:v:0]${vf.join(',')}[v${vi}]`);
      const af=['aresample=48000','asetpts=PTS-STARTPTS',atempo(speed),`volume=${Math.max(0,Math.min(4,Number(clip.volume??1)))}`];if(Number(clip.fadeIn||0)>0)af.push(`afade=t=in:st=0:d=${Math.min(Number(clip.fadeIn),dur)}`);if(Number(clip.fadeOut||0)>0){const fo=Math.min(Number(clip.fadeOut),dur);af.push(`afade=t=out:st=${Math.max(0,dur-fo)}:d=${fo}`);}afLabels.push(`[${audio?input:input+1}:a:0]${af.join(',')}[a${vi}]`);
    }
    let filter=`${vfLabels.join(';')};${afLabels.join(';')};`;
    const vcat=vfLabels.map((_,i)=>`[v${i}]`).join('');const acat=afLabels.map((_,i)=>`[a${i}]`).join('');
    filter+=`${vcat}concat=n=${videos.length}:v=1:a=0[vout];${acat}concat=n=${afLabels.length}:v=0:a=1[basea];`;
    const audioMix=['[basea]'];
    const externals=timeline.tracks.filter((t:any)=>t.type==='audio'&&!t.muted).flatMap((t:any)=>t.clips.filter((c:any)=>c.duration>0));
    for(const clip of externals){const asset:any=db.prepare('SELECT * FROM assets WHERE id=?').get(clip.assetId);if(!asset||!existsSync(asset.path)||!hasAudio(asset.path))continue;const input=next++;inputs.push('-ss',String(clip.trimStart),'-t',String(Math.max(.01,clip.trimEnd-clip.trimStart)),'-i',asset.path);const vol=Math.max(0,Math.min(4,Number(clip.volume??1)));const delay=Math.max(0,Math.round(Number(clip.startTime||0)*1000));filter+=`[${input}:a:0]aresample=48000,volume=${vol},adelay=${delay}:all=1[ma${input}];`;audioMix.push(`[ma${input}]`);}
    if(audioMix.length===1)filter+='[basea]anull[aout]';else filter+=`${audioMix.join('')}amix=inputs=${audioMix.length}:duration=longest:dropout_transition=0:normalize=0[aout]`;
    const output=join(EXPORTS,`${randomUUID()}.mp4`);const result=spawnSync('ffmpeg',['-y',...inputs,'-filter_complex',filter,'-map','[vout]','-map','[aout]','-c:v','libx264','-preset','veryfast','-pix_fmt','yuv420p','-c:a','aac','-movflags','+faststart',output],{encoding:'utf8',timeout:180000});if(result.status!==0||!existsSync(output))return res.status(500).json({error:'FFmpeg advanced render failed',detail:result.stderr?.slice(-4000)});res.download(output,'ai-creative-studio.mp4',()=>{try{unlinkSync(output);}catch{}});
  }catch(error){console.error('advanced render failed',error);res.status(500).json({error:'Advanced render failed'});}
}

export function registerAIRoute(app:Express,db:Database.Database){
  app.post('/api/projects/:id/ai-command',async(req,res)=>{
    try{
      const projectId=String(req.params.id);const p:any=db.prepare('SELECT * FROM projects WHERE id=?').get(projectId);if(!p)return res.status(404).json({error:'Project not found'});
      const timeline=JSON.parse(p.timeline_json);timeline.currentTime=Number(req.body?.playhead??timeline.currentTime??0);const activeClipId=String(req.body?.clipId||'');const fallback:EditCommand={type:'noop',message:'يمكنني تنفيذ أدوات التحرير المتاحة من شريط الأدوات.'};const command=await parseWithOpenAI(String(req.body?.text||''),timeline,fallback,activeClipId);
      if(command.type==='noop')return res.json({provider:process.env.AI_API_KEY||process.env.OPENAI_API_KEY?'ai':'local',command,timeline});
      const out=structuredClone(timeline);let owner:any=null;let target:any=null;for(const track of out.tracks){const found=track.clips?.find((c:any)=>c.id===command.clipId);if(found){owner=track;target=found;break;}}if(!target&&command.type!=='add_text'){for(const track of out.tracks){if(track.clips?.length){owner=track;target=track.clips[0];break;}}}
      if(command.type==='add_text'){let track=out.tracks.find((t:any)=>t.type==='text');if(!track){track={id:randomUUID(),name:'Text',type:'text',clips:[],muted:false,locked:false,visible:true,height:64,order:2};out.tracks.push(track);}const start=Math.max(0,Number(command.time??out.currentTime??0));track.clips.push({id:randomUUID(),assetId:'',name:command.text||'نص',text:command.text||'نص جديد',startTime:start,endTime:start+3,trimStart:0,trimEnd:3,duration:3,fontSize:48,color:'#ffffff',opacity:1,align:'center',position:'center',keyframes:[]});}
      else if(!target)return res.json({provider:'local',command:{type:'noop',message:'لا يوجد مقطع يمكن تعديله.'},timeline});
      else{target.effects=Array.isArray(target.effects)?target.effects:[];if(command.type==='split'){const t=Number(command.time);if(!(t>target.startTime&&t<target.endTime))return res.json({provider:'local',command:{type:'noop',message:`نقطة التقسيم ${t.toFixed(2)} ثانية خارج المقطع.`},timeline});const ratio=(t-target.startTime)/(target.endTime-target.startTime);const second=structuredClone(target);second.id=randomUUID();second.startTime=t;second.endTime=target.endTime;second.duration=second.endTime-second.startTime;second.trimStart=target.trimStart+(target.trimEnd-target.trimStart)*ratio;target.endTime=t;target.duration=t-target.startTime;owner.clips.splice(owner.clips.indexOf(target),1,target,second);}else if(command.type==='delete')owner.clips=owner.clips.filter((c:any)=>c.id!==target.id);else if(command.type==='move'){const s=Math.max(0,Number(command.startTime||0));target.startTime=s;target.endTime=s+target.duration;}else if(command.type==='trim_start'){const s=Math.max(0,Number(command.time||0));if(s>=target.trimEnd)return res.json({provider:'local',command:{type:'noop',message:'قيمة القص أكبر من مدة المقطع.'},timeline});const d=s-target.trimStart;target.trimStart=s;target.startTime=Math.max(0,target.startTime+d);target.duration=Math.max(.01,target.endTime-target.startTime);}else if(command.type==='trim_end'){const e=Math.max(target.trimStart+.01,Number(command.time||target.trimEnd));target.trimEnd=Math.min(e,target.trimEnd);target.endTime=target.startTime+(target.trimEnd-target.trimStart);target.duration=Math.max(.01,target.endTime-target.startTime);}else if(command.type==='set_volume')target.volume=Math.max(0,Math.min(4,Number(command.value??1)));else if(command.type==='set_speed')target.speed=Math.max(.25,Math.min(4,Number(command.value??1)));else if(command.type==='rotate')target.rotate=((Number(command.value??90)%360)+360)%360;else if(command.type==='flip_h')target.flipH=!target.flipH;else if(command.type==='flip_v')target.flipV=!target.flipV;else if(command.type==='set_brightness')target.brightness=Math.max(-1,Math.min(1,Number(command.value??0)));else if(command.type==='set_contrast')target.contrast=Math.max(.1,Math.min(4,Number(command.value??1)));else if(command.type==='set_saturation')target.saturation=Math.max(0,Math.min(4,Number(command.value??1)));else if(command.type==='grayscale')target.grayscale=!target.grayscale;else if(command.type==='fade_in')target.fadeIn=Math.max(.1,Number(command.value??1));else if(command.type==='fade_out')target.fadeOut=Math.max(.1,Number(command.value??1));else if(command.type==='set_effect'){const effect=String(command.effect||'').toLowerCase();target.effects=target.effects.filter((e:string)=>e!==effect);if(effect)target.effects.push(effect);}else if(command.type==='set_transition')target.transition={type:command.transition||'fade',duration:Math.max(.1,Number(command.value??.5))};else if(command.type==='set_text')target.text=command.text||target.text||'';}
      out.tracks.forEach((t:any)=>t.clips.sort((a:any,b:any)=>a.startTime-b.startTime));out.duration=Math.max(0,...out.tracks.flatMap((t:any)=>t.clips.map((c:any)=>c.endTime)));out.currentTime=Number(command.time??out.currentTime??0);const history=JSON.parse(p.history_json).slice(0,Number(p.history_index)+1);history.push(out);const bounded=history.slice(-100);db.prepare('UPDATE projects SET timeline_json=?,history_json=?,history_index=?,updated_at=? WHERE id=?').run(JSON.stringify(out),JSON.stringify(bounded),bounded.length-1,new Date().toISOString(),projectId);res.json({provider:process.env.AI_BASE_URL||process.env.AI_API_KEY||process.env.OPENAI_API_KEY?'ai':'local',command,timeline:out});
    }catch(error){console.error('ai-command failed',error);res.status(500).json({error:'Failed to execute AI command'});}
  });
  app.post('/api/projects/:id/render-advanced',(req,res)=>advancedRender(req,res,db));
  const stack:any[]=(app as any)._router?.stack||[];const renderLayer=stack.find(l=>l?.route?.path==='/api/projects/:id/render');if(renderLayer?.route?.stack?.[0])renderLayer.route.stack[0].handle=(req:Request,res:Response)=>advancedRender(req,res,db);
}
