import { BaseEngine, EngineConfigSchema } from '@ai-creative-studio/core';
import { EventEmitter } from 'eventemitter3';
import { z } from 'zod';
import { v4 as uuidv4 } from 'uuid';

const AnimationEngineConfigSchema = EngineConfigSchema.extend({
  defaultEasing: z.enum(['linear', 'ease-in', 'ease-out', 'ease-in-out']).optional().default('ease-in-out'),
  defaultDuration: z.number().optional().default(0.5),
});
type AnimationEngineConfig = z.infer<typeof AnimationEngineConfigSchema>;

export interface IAnimation { id:string; name:string; type:AnimationType; startTime:number; duration:number; delay:number; easing:EasingType; iterations:number; direction:'normal'|'reverse'|'alternate'|'alternate-reverse'; fillMode:'none'|'forwards'|'backwards'|'both'; keyframes:IAnimationKeyframe[]; targetId:string; property:string; enabled:boolean; }
export type AnimationType='transform'|'opacity'|'color'|'filter'|'width'|'height'|'position'|'scale'|'rotation'|'custom';
export interface IAnimationKeyframe { id:string; offset:number; properties:Record<string,AnimationValue>; easing:EasingType; easingFunction?: (t:number)=>number; }
export type AnimationValue=number|string|{[key:string]:number};
export interface ITweenOptions { duration?:number; delay?:number; easing?:EasingType; iterations?:number; direction?:IAnimation['direction']; fillMode?:IAnimation['fillMode']; }
export interface IAnimationEvaluation { time:number; progress:number; animationId:string; targetId:string; properties:Record<string,AnimationValue>; }
export interface IAnimationEvents { 'animation:created':{animation:IAnimation}; 'animation:removed':{animationId:string}; 'animation:started':{animationId:string}; 'animation:completed':{animationId:string}; 'animation:iteration':{animationId:string;iteration:number}; 'animation:cancelled':{animationId:string}; 'animation:keyframe:added':{animationId:string;keyframe:IAnimationKeyframe}; 'animation:keyframe:removed':{animationId:string;keyframeId:string}; }
export type EasingFunction=(t:number)=>number;
function cubicBezierAt(x1:number,y1:number,x2:number,y2:number,x:number):number{const clamp=(v:number)=>Math.max(0,Math.min(1,v));const cx=3*x1,bx=3*(x2-x1)-cx,ax=1-cx-bx,cy=3*y1,by=3*(y2-y1)-cy,ay=1-cy-by;const sx=(t:number)=>((ax*t+bx)*t+cx)*t,sy=(t:number)=>((ay*t+by)*t+cy)*t,dx=(t:number)=>(3*ax*t+2*bx)*t+cx,target=clamp(x);let t=target;for(let i=0;i<8;i++){const e=sx(t)-target,d=dx(t);if(Math.abs(e)<1e-7||Math.abs(d)<1e-7)break;t=clamp(t-e/d)}let lo=0,hi=1;for(let i=0;i<12;i++){const mid=(lo+hi)/2;if(sx(mid)<target)lo=mid;else hi=mid}const candidate=Math.abs(sx(t)-target)<1e-5?t:(lo+hi)/2;return clamp(sy(candidate));}
export const EasingFunctions:Record<EasingType,EasingFunction>={'linear':t=>t,'ease-in':t=>t*t*t,'ease-out':t=>1-Math.pow(1-t,3),'ease-in-out':t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2,'bounce':t=>{const n=7.5625,d=2.75;if(t<1/d)return n*t*t;if(t<2/d)return n*(t-=1.5/d)*t+.75;if(t<2.5/d)return n*(t-=2.25/d)*t+.9375;return n*(t-=2.625/d)*t+.984375},'elastic':t=>{const c=(2*Math.PI)/3;return t===0?0:t===1?1:Math.pow(2,-10*t)*Math.sin((10*t-.75)*c)+1},'back':t=>{const c1=1.70158,c3=c1+1;return 1+c3*Math.pow(t-1,3)+c1*Math.pow(t-1,2)},'cubic-bezier':t=>cubicBezierAt(.42,0,.58,1,t)};

export class AnimationEngine extends BaseEngine {
  private animations=new Map<string,IAnimation>(); private activeAnimations=new Set<string>(); private emitter=new EventEmitter<IAnimationEvents>(); private defaultEasing:EasingType; private defaultDuration:number; private animationCallbacks=new Map<string,(evaluation:IAnimationEvaluation)=>void>();
  constructor(config:AnimationEngineConfig){const parsed=AnimationEngineConfigSchema.parse(config);super(parsed as any);this.defaultEasing=parsed.defaultEasing;this.defaultDuration=parsed.defaultDuration;}
  protected async onInitialize():Promise<void>{}
  protected override async onDestroy():Promise<void>{this.animations.clear();this.activeAnimations.clear();this.animationCallbacks.clear();}
  createAnimation(type:AnimationType,targetId:string,property:string,options:{name?:string;startTime?:number;duration?:number;delay?:number;easing?:EasingType;iterations?:number;direction?:IAnimation['direction'];fillMode?:IAnimation['fillMode']}={}):IAnimation{const animation:IAnimation={id:uuidv4(),name:options.name||`${type}-${property}`,type,startTime:options.startTime??0,duration:Math.max(Number.EPSILON,options.duration??this.defaultDuration),delay:options.delay??0,easing:options.easing??this.defaultEasing,iterations:options.iterations??1,direction:options.direction??'normal',fillMode:options.fillMode??'none',keyframes:[],targetId,property,enabled:true};this.animations.set(animation.id,animation);this.emitter.emit('animation:created',{animation});return animation;}
  removeAnimation(id:string):void{const a=this.animations.get(id);if(!a)return;this.stopAnimation(id);this.animations.delete(id);this.emitter.emit('animation:removed',{animationId:id});}
  getAnimation(id:string):IAnimation|undefined{return this.animations.get(id);}
  getAnimationsByTarget(targetId:string):IAnimation[]{return [...this.animations.values()].filter(a=>a.targetId===targetId);}
  getAnimationsByProperty(targetId:string,property:string):IAnimation[]{return [...this.animations.values()].filter(a=>a.targetId===targetId&&a.property===property);}
  addKeyframe(animationId:string,offset:number,properties:Record<string,AnimationValue>,easing?:EasingType):IAnimationKeyframe|null{const a=this.animations.get(animationId);if(!a)return null;const k:IAnimationKeyframe={id:uuidv4(),offset:Math.max(0,Math.min(1,offset)),properties,easing:easing??a.easing};const i=a.keyframes.findIndex(x=>x.offset>k.offset);if(i===-1)a.keyframes.push(k);else a.keyframes.splice(i,0,k);this.emitter.emit('animation:keyframe:added',{animationId,keyframe:k});return k;}
  removeKeyframe(animationId:string,keyframeId:string):void{const a=this.animations.get(animationId);if(!a)return;const i=a.keyframes.findIndex(k=>k.id===keyframeId);if(i<0)return;a.keyframes.splice(i,1);this.emitter.emit('animation:keyframe:removed',{animationId,keyframeId});}
  updateKeyframe(animationId:string,keyframeId:string,updates:Partial<IAnimationKeyframe>):void{const a=this.animations.get(animationId);const k=a?.keyframes.find(x=>x.id===keyframeId);if(k)Object.assign(k,updates);}
  startAnimation(id:string):void{const a=this.animations.get(id);if(!a||!a.enabled)return;this.activeAnimations.add(id);this.emitter.emit('animation:started',{animationId:id});}
  stopAnimation(id:string):void{if(!this.activeAnimations.has(id))return;this.activeAnimations.delete(id);this.emitter.emit('animation:completed',{animationId:id});}
  cancelAnimation(id:string):void{this.activeAnimations.delete(id);this.emitter.emit('animation:cancelled',{animationId:id});}
  evaluate(animationId:string,time:number):IAnimationEvaluation|null{const a=this.animations.get(animationId);if(!a||!a.enabled)return null;const adjusted=time-a.startTime-a.delay;if(adjusted<0&&a.fillMode!=='backwards'&&a.fillMode!=='both')return null;let progress=adjusted/a.duration;let iteration=0;if(progress>=1&&a.iterations!==Infinity){if(progress>=a.iterations)progress=1;else{iteration=Math.floor(progress);progress%=1;}}if(a.direction==='reverse')progress=1-progress;else if(a.direction==='alternate')progress=iteration%2===0?progress:1-progress;else if(a.direction==='alternate-reverse')progress=iteration%2===1?progress:1-progress;progress=Math.max(0,Math.min(1,progress));return{time,progress,animationId:a.id,targetId:a.targetId,properties:this.interpolateKeyframes(a,progress)};}
  private interpolateKeyframes(a:IAnimation,progress:number):Record<string,AnimationValue>{const k=a.keyframes;if(!k.length)return{};if(k.length===1)return k[0].properties;let start=k[0],end=k[k.length-1];for(let i=0;i<k.length-1;i++){if(progress>=k[i].offset&&progress<=k[i+1].offset){start=k[i];end=k[i+1];break;}}const span=end.offset-start.offset;const local=span<=Number.EPSILON?1:Math.max(0,Math.min(1,(progress-start.offset)/span));const t=EasingFunctions[start.easing](local);const out:Record<string,AnimationValue>={};for(const[key,v]of Object.entries(end.properties)){const sv=start.properties[key];if(sv===undefined){out[key]=v;continue;}if(typeof v==='number'&&typeof sv==='number')out[key]=sv+(v-sv)*t;else if(typeof v==='string'&&typeof sv==='string')out[key]=t<.5?sv:v;else if(typeof v==='object'&&typeof sv==='object')out[key]=this.interpolateObjects(sv as Record<string,number>,v as Record<string,number>,t);else out[key]=v;}return out;}
  private interpolateObjects(start:Record<string,number>,end:Record<string,number>,t:number):Record<string,number>{const out:Record<string,number>={};for(const[key,v]of Object.entries(end))out[key]=(start[key]??v)+(v-(start[key]??v))*t;return out;}
  update(time:number):Map<string,IAnimationEvaluation>{const out=new Map<string,IAnimationEvaluation>();this.activeAnimations.forEach(id=>{const e=this.evaluate(id,time);if(e){out.set(id,e);const cb=this.animationCallbacks.get(id);cb?.(e);}});return out;}
  setAnimationCallback(id:string,callback:(evaluation:IAnimationEvaluation)=>void):void{this.animationCallbacks.set(id,callback);}
  tween(targetId:string,from:Record<string,AnimationValue>,to:Record<string,AnimationValue>,options:ITweenOptions={}):IAnimation{const keys=Object.keys({...from,...to});const a=this.createAnimation('custom',targetId,keys.join(','),options);this.addKeyframe(a.id,0,from,options.easing);this.addKeyframe(a.id,1,to,options.easing);return a;}
  fade(targetId:string,fromOpacity:number,toOpacity:number,options?:ITweenOptions):IAnimation{return this.tween(targetId,{opacity:fromOpacity},{opacity:toOpacity},options);}
  move(targetId:string,from:{x:number;y:number},to:{x:number;y:number},options?:ITweenOptions):IAnimation{return this.tween(targetId,{x:from.x,y:from.y},{x:to.x,y:to.y},options);}
  scale(targetId:string,from:{x:number;y:number},to:{x:number;y:number},options?:ITweenOptions):IAnimation{return this.tween(targetId,{scaleX:from.x,scaleY:from.y},{scaleX:to.x,scaleY:to.y},options);}
  rotate(targetId:string,from:number,to:number,options?:ITweenOptions):IAnimation{return this.tween(targetId,{rotation:from},{rotation:to},options);}
  onAnimation<E extends keyof IAnimationEvents>(event:E,listener:(data:IAnimationEvents[E])=>void):this{this.emitter.on(event,listener as any);return this;}
  offAnimation<E extends keyof IAnimationEvents>(event:E,listener:(data:IAnimationEvents[E])=>void):this{this.emitter.off(event,listener as any);return this;}
  getCapabilities():string[]{return['animation:create','animation:remove','animation:start','animation:stop','animation:cancel','animation:keyframes','animation:easing','animation:interpolation','animation:tweens','animation:transforms','animation:opacity','animation:color','animation:filters'];}
}
