import { BaseEngine, EngineConfigSchema, ProjectId, ProjectGraph, NodeId, Resolution, FrameRate } from '@ai-creative-studio/core';
import { EventEmitter } from 'eventemitter3';
import { z } from 'zod';
import { v4 as uuidv4 } from 'uuid';

const ProjectEngineConfigSchema = EngineConfigSchema.extend({
  autoSaveInterval: z.number().optional().default(30000),
  maxBackups: z.number().optional().default(10),
  cloudSync: z.boolean().optional().default(false),
});
type ProjectEngineConfig = z.infer<typeof ProjectEngineConfigSchema>;

export type ProjectType='video'|'design'|'motion'|'audio'|'presentation'|'image'|'brand'|'3d'|'animation';
export interface IProjectSettings{resolution:Resolution;frameRate:FrameRate;duration:number;qualityPreset:'draft'|'preview'|'final'|'custom';colorProfile:'srgb'|'p3'|'rec709'|'rec2020';pixelAspectRatio:number;renderSettings:IRenderSettings;}
export interface IRenderSettings{codec:'h264'|'h265'|'vp9'|'prores'|'dnxhd';quality:number;audioCodec:'aac'|'opus'|'pcm'|'flac';audioQuality:number;pixelFormat:'yuv420p'|'yuv422p'|'yuv444p'|'rgb24';preset:'ultrafast'|'fast'|'medium'|'slow';}
export interface IProjectMetadata{title:string;description?:string;author?:string;tags:string[];version:string;createdAt:number;updatedAt:number;templateId?:string;}
export interface IScene{id:string;name:string;duration:number;layers:ILayer[];markers:IMarker[];backgroundColor?:string;transitions?:ITransition[];}
export interface ILayer{id:string;name:string;type:'video'|'audio'|'text'|'image'|'shape'|'group'|'effect';visible:boolean;locked:boolean;opacity:number;blendMode:string;transform:{position:{x:number;y:number};scale:{x:number;y:number};rotation:number;anchor:{x:number;y:number}};effects:string[];animations:string[];children?:ILayer[];}
export interface IMarker{id:string;time:number;name:string;color:string;}
export interface ITransition{type:'cut'|'fade'|'dissolve'|'wipe'|'slide'|'zoom';duration:number;direction?:'left'|'right'|'up'|'down';}
export interface IFullProject{id:ProjectId;type:ProjectType;settings:IProjectSettings;metadata:IProjectMetadata;graph:ProjectGraph;scenes:IScene[];assets:NodeId[];timelineData:unknown;activeSceneId:string;}
export interface IProjectBackup{id:string;projectId:ProjectId;timestamp:number;label?:string;size:number;data:unknown;}
export interface IProjectPersistence{save(project:IFullProject):Promise<void>;load(projectId:ProjectId):Promise<IFullProject|null>}
export interface IProjectEvents{'project:created':{project:IFullProject};'project:loaded':{project:IFullProject};'project:saved':{projectId:ProjectId};'project:closed':{projectId:ProjectId};'project:settings-changed':{projectId:ProjectId;settings:IProjectSettings};'project:scene-added':{projectId:ProjectId;scene:IScene};'project:scene-removed':{projectId:ProjectId;sceneId:string};'project:auto-save':{projectId:ProjectId};'project:backup-created':{backup:IProjectBackup};}

export class ProjectEngine extends BaseEngine{
  private projects=new Map<ProjectId,IFullProject>(); private activeProjectId:ProjectId|null=null; private backups=new Map<ProjectId,IProjectBackup[]>(); private autoSaveTimer:NodeJS.Timeout|null=null; private projectEmitter=new EventEmitter<IProjectEvents>(); private autoSaveInterval:number; private maxBackups:number; private persistence?:IProjectPersistence; private cloudSync:boolean;
  constructor(config:ProjectEngineConfig,options:{persistence?:IProjectPersistence}={}){const parsed=ProjectEngineConfigSchema.parse(config);super(parsed as any);this.autoSaveInterval=parsed.autoSaveInterval;this.maxBackups=parsed.maxBackups;this.persistence=options.persistence;this.cloudSync=parsed.cloudSync;}
  protected async onInitialize():Promise<void>{if(this.autoSaveInterval>0)this.autoSaveTimer=setInterval(()=>void this.autoSaveAll(),this.autoSaveInterval);}
  protected override async onDestroy():Promise<void>{if(this.autoSaveTimer)clearInterval(this.autoSaveTimer);this.autoSaveTimer=null;this.projects.clear();this.backups.clear();}
  createProject(type:ProjectType,name:string,template:{settings?:Partial<IProjectSettings>;scenes?:Partial<IScene>[]}={}):IFullProject{const id=uuidv4() as ProjectId;const sceneId=uuidv4();const settings:IProjectSettings={resolution:template.settings?.resolution??{width:1920,height:1080,pixelAspectRatio:1},frameRate:template.settings?.frameRate??30,duration:template.settings?.duration??0,qualityPreset:template.settings?.qualityPreset??'preview',colorProfile:template.settings?.colorProfile??'srgb',pixelAspectRatio:template.settings?.pixelAspectRatio??1,renderSettings:template.settings?.renderSettings??{codec:'h264',quality:80,audioCodec:'aac',audioQuality:192,pixelFormat:'yuv420p',preset:'medium'}};const scenes=template.scenes?.map((s,i)=>({id:uuidv4(),name:s.name??`Scene ${i+1}`,duration:s.duration??5,layers:s.layers??[],markers:s.markers??[],backgroundColor:s.backgroundColor??'#000000',transitions:s.transitions??[]}))??[{id:sceneId,name:'Scene 1',duration:5,layers:[],markers:[],backgroundColor:'#000000',transitions:[]}];const project:IFullProject={id,type,settings,metadata:{title:name,tags:[],version:'1.0.0',createdAt:Date.now(),updatedAt:Date.now()},graph:new ProjectGraph(id),scenes,assets:[],timelineData:null,activeSceneId:scenes[0].id};project.graph.addNode('project',{name,inputs:{type,settings}});this.projects.set(id,project);this.backups.set(id,[]);if(!this.activeProjectId)this.activeProjectId=id;this.projectEmitter.emit('project:created',{project});return project;}
  loadProject(projectId:ProjectId,data:unknown):IFullProject{const parsed=JSON.parse(JSON.stringify(data)) as IFullProject;parsed.graph=ProjectGraph.deserialize(parsed.graph as any);this.projects.set(projectId,parsed);this.backups.set(projectId,[]);if(!this.activeProjectId)this.activeProjectId=projectId;this.projectEmitter.emit('project:loaded',{project:parsed});return parsed;}
  closeProject(projectId:ProjectId):void{if(!this.projects.has(projectId))return;this.saveProject(projectId);if(this.activeProjectId===projectId)this.activeProjectId=Array.from(this.projects.keys()).find(id=>id!==projectId)||null;this.projects.delete(projectId);this.projectEmitter.emit('project:closed',{projectId});}
  saveProject(projectId:ProjectId):void{const project=this.projects.get(projectId);if(!project)return;project.metadata.updatedAt=Date.now();this.projectEmitter.emit('project:saved',{projectId});if(this.persistence)void this.persistence.save(this.cloneForPersistence(project)).catch(()=>{});}
  async persistProject(projectId:ProjectId):Promise<void>{const project=this.projects.get(projectId);if(!project||!this.persistence)throw new Error('Project persistence adapter is not configured');await this.persistence.save(this.cloneForPersistence(project));}
  async hydrateProject(projectId:ProjectId):Promise<IFullProject|null>{if(!this.persistence)return null;const project=await this.persistence.load(projectId);if(!project)return null;project.graph=project.graph instanceof ProjectGraph?project.graph:ProjectGraph.deserialize((project.graph as any));this.projects.set(projectId,project);this.backups.set(projectId,[]);if(!this.activeProjectId)this.activeProjectId=projectId;this.projectEmitter.emit('project:loaded',{project});return project;}
  getProject(id:ProjectId):IFullProject|undefined{return this.projects.get(id);} getActiveProject():IFullProject|undefined{return this.activeProjectId?this.projects.get(this.activeProjectId):undefined;} getActiveProjectId():ProjectId|undefined{return this.activeProjectId??undefined;} setActiveProject(id:ProjectId):void{if(this.projects.has(id))this.activeProjectId=id;}
  updateSettings(id:ProjectId,settings:Partial<IProjectSettings>):void{const p=this.projects.get(id);if(!p)return;Object.assign(p.settings,settings);p.metadata.updatedAt=Date.now();this.projectEmitter.emit('project:settings-changed',{projectId:id,settings:p.settings});}
  addScene(id:ProjectId,scene:Partial<IScene>={}):IScene{const p=this.projects.get(id);if(!p)throw new Error('Project not found');const s:IScene={id:uuidv4(),name:scene.name??`Scene ${p.scenes.length+1}`,duration:scene.duration??5,layers:scene.layers??[],markers:scene.markers??[],backgroundColor:scene.backgroundColor??'#000000',transitions:scene.transitions??[]};p.scenes.push(s);p.metadata.updatedAt=Date.now();this.projectEmitter.emit('project:scene-added',{projectId:id,scene:s});return s;}
  removeScene(id:ProjectId,sceneId:string):void{const p=this.projects.get(id);if(!p)return;const i=p.scenes.findIndex(s=>s.id===sceneId);if(i<0)return;p.scenes.splice(i,1);if(p.activeSceneId===sceneId&&p.scenes.length)p.activeSceneId=p.scenes[0].id;p.metadata.updatedAt=Date.now();this.projectEmitter.emit('project:scene-removed',{projectId:id,sceneId});}
  getScene(id:ProjectId,sceneId:string):IScene|undefined{return this.projects.get(id)?.scenes.find(s=>s.id===sceneId);} updateScene(id:ProjectId,sceneId:string,updates:Partial<IScene>):void{const s=this.getScene(id,sceneId);const p=this.projects.get(id);if(!s||!p)return;Object.assign(s,updates);p.metadata.updatedAt=Date.now();}
  createBackup(id:ProjectId,label?:string):IProjectBackup{const p=this.projects.get(id);if(!p)throw new Error('Project not found');const list=this.backups.get(id)||[];const data=JSON.parse(this.serializeProject(id));const b:IProjectBackup={id:uuidv4(),projectId:id,timestamp:Date.now(),label,size:JSON.stringify(data).length,data};list.push(b);while(list.length>this.maxBackups)list.shift();this.backups.set(id,list);this.projectEmitter.emit('project:backup-created',{backup:b});return b;}
  restoreFromBackup(id:ProjectId,backupId:string):void{const b=(this.backups.get(id)||[]).find(x=>x.id===backupId);if(!b)throw new Error('Backup not found');const project=JSON.parse(JSON.stringify(b.data)) as IFullProject;project.graph=ProjectGraph.deserialize(project.graph as any);project.metadata.updatedAt=Date.now();this.projects.set(id,project);this.projectEmitter.emit('project:loaded',{project});}
  getBackups(id:ProjectId):IProjectBackup[]{return [...(this.backups.get(id)||[])];}
  private async autoSaveAll():Promise<void>{for(const [id]of this.projects){this.saveProject(id);this.projectEmitter.emit('project:auto-save',{projectId:id});}}
  serializeProject(id:ProjectId):string{const p=this.projects.get(id);if(!p)throw new Error('Project not found');return JSON.stringify({...p,graph:p.graph.serialize()});}
  getAllProjects():IFullProject[]{return [...this.projects.values()];}
  private cloneForPersistence(project:IFullProject):IFullProject{const serialized=JSON.parse(this.serializeProject(project.id));serialized.graph=ProjectGraph.deserialize(serialized.graph);return serialized;}
  onProject<E extends keyof IProjectEvents>(event:E,listener:(data:IProjectEvents[E])=>void):this{this.projectEmitter.on(event,listener as any);return this} offProject<E extends keyof IProjectEvents>(event:E,listener:(data:IProjectEvents[E])=>void):this{this.projectEmitter.off(event,listener as any);return this}
  getCapabilities():string[]{const out=['project:create','project:load','project:save','project:close','project:settings','scene:create','scene:delete','scene:update','project:backup','project:restore'];if(this.persistence)out.push('project:persistence');if(this.cloudSync)out.push('project:cloud-sync-configured');return out;}
}
